name: Lint Check
# unuse check.

on: 
  push:
    branches:
    - features/*
  pull_request:
    branches:
    - features/*

jobs:
  hadolint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: brew install hadolint
    - name: hadolint
      run: hadolint ./Dockerfile
